### ISSUE TITLE
Sponsored: ability to run aditional system services

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#4719] opened 2021-12-22 15:55 UTC
## Description

We would like to see a way to add some "packages"/"containers" in talos as are machined / apid / udevd
They could be plain containers (not pods) or packages to be installed. They would give us a way to deploy some additional services needed for running kubernetes.
One example is to run a consul agent that will announce to its servers that the apiserver is available. This provides an easy path to add a master to a loadbalancer as soon as it is available.
One other example is  running a bgp server annoucing routes like bird.

**Comment by andrewrynhard** [comment] 2021-12-22 17:43
Questions:

  - How does Consul know that the API server is up?

**Comment by andrewrynhard** [comment] 2021-12-22 17:52
See #4727 as a potential way to run Consul.

**Comment by sbskas** [comment] 2021-12-22 22:54
Consul allows to declare services and services checks.
The agent announces a service 'kube-apiserver' which can be up or down according to the result of check.
The example of consul is a really complicated one with a directory containing a set of hcl / json snippets which can can added or removed dynamically and a /var/lib/consul binary data which contains stateful informations (name of servers to contact, keys to use and so on...).
I have two other examples:
1-[talos-vmtoolsd](https://github.com/mologie/talos-vmtoolsd)
2-ntpd if one want to use the plain old server

Below is an example of an apiserver check.
Apiserver show up as A RECORD  for the fqdn  cluster1.kube-apiserver.service.<domain>.consul.
```
services {
  name = "kube-apiserver"
  address = ""
  port = 6443
  tags = [ "cluster1" ]
  check {
    id = "api",
    name = "HTTP API on port 6443",
    "http" = "https://localhost:6443/healthz",
    "tls_skip_verify" = true,
    "method" = "GET",
    "interval" = "10s",
    "timeout" = "5s"
  }
}
```

**Comment by smira** [comment] 2021-12-23 12:48
I think consul agent is a perfect example of something which can be run as a static pod. Either configs are baked in into the custom image, or they're written to disk via Talos machine config user files option and mounted into the static pod. 

In #4727 we can add a support for custom static pods which can be easily updated/removed on the fly. 

Consul agent should be up when Kubernetes is up, and it doesn't affect host OS behavior.

**Comment by sbskas** [comment] 2022-01-05 18:51
Some documentation of how to do it with the static pods would be appreciated.

**Comment by andrewrynhard** [comment] 2022-01-05 19:31
One thing that came up in discussions is that it would be great if custom services had an API for starting and stopping in addition to the restart we already have.

**Comment by smira** [comment] 2022-01-13 12:05
> Some documentation of how to do it with the static pods would be appreciated.

we don't have this feature yet, but the tracking issue is #4727. 

At the moment static pods can be created via `.machine.files` in the machine configuration by placing `.yaml` static pod definition to `/etc/kubernetes/manifests`. Once #4727 is implemented, there will be an easier way to do it.

**Comment by smira** [comment] 2022-01-26 17:45
Closing as duplicate of #4727

**Closed by smira** 2022-01-26 17:45 UTC
